import Head from "next/head";
import Header from "../components/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Hello World</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <Header />
        <h1>Hello World</h1>
      </main>
    </>
  );
}
